name: sukuu_parent
description: Sukuu Parent - A school app for parents to view their children's info and grades
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  pdf: ^3.10.7
  printing: ^5.13.5
  fl_chart: ^0.66.0
  path_provider: ^2.1.4
  url_launcher: ^6.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  flutter_launcher_icons: ^0.13.1


flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: false
  image_path: "school_icon.png"
